changeLogFile: db/changelog/db.changelog-master.yaml
searchPath: /workspace,/workspace/db/changelog
url: jdbc:postgresql://host.docker.internal:5432/liquibase_demo
username: liquibase
password: password
driver: org.postgresql.Driver
classpath: /opt/liquibase/lib/postgresql.jar